spring.application.name=cfg-engine
server.port=8080

# Logging
logging.level.root=INFO
logging.level.com.unl.automatas=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Servlet configuration
server.servlet.context-path=/
spring.mvc.log-request-details=false
